# Server Port configuration
server.port=8085

# Spring Mail properties for Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akashportfolio333@gmail.com
# Use an App Password here, NOT your main account password
# Obtain from Google Account settings -> Security -> 2-Step Verification -> App passwords
spring.mail.password=uscxqnqaoiqqzsxr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging levels
logging.level.org.springframework.web=info
logging.level.com.akash.portfolio=debug
